service: todo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

package:
  include:
    - dist/**
	
functions:
  api:
    handler: dist/api/task/index.handler
    environment:
      AWS_SQS_QUEUE_URL: !GetAtt EmailQueue.QueueUrl
      AWS_SQS_EMAIL_NOTIFICATION: rafaellevissa@gmail.com # change here where you should receive the email once the task is done

    events:
      - http: ANY /task
      - http: 'ANY /task/{proxy+}'

  emailWorker:
    handler: dist/worker/email-worker.handler
    events:
      - sqs:
          arn: !GetAtt EmailQueue.Arn

resources:
  Resources:
    SESLambdaPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: SESLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
              Resource: '*'
        Roles:
          - !Ref "IamRoleLambdaExecution"

    EmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: email-queue

    LambdaEmailSQSPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: LambdaSQSPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:SendMessage'
              Resource: !GetAtt EmailQueue.Arn
        Roles:
          - !Ref "IamRoleLambdaExecution"

    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasks-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    TaskTablePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: TaskTablePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'
              Resource: !GetAtt TaskTable.Arn
        Roles:
          - !Ref "IamRoleLambdaExecution"

